name: Update Profile Stats
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
permissions:
  contents: write  # 赋予 GITHUB_TOKEN 写入权限
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 关闭默认凭证（避免冲突）
          
      - name: Update README
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/linjonh/linjonh/traffic/views \
               | jq '.count' > views.txt
          sed -i "s/<!-- VIEWS -->/$(cat views.txt)/g" README.md
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto Updated views count"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/linjonh/linjonh.git
          git push origin main
